name: SWE Homework
on: workflow_dispatch
    pull_request:
    push:
      - master
      - develop
jobs:
  build:
    runs-on: ubuntu-latest
steps:
  - uses: actions/checkout@v3
  - uses: actions/setup-java@v3
    with:
      java-version: '11'
      distribution: 'adopt'
  - name: Run the Maven verify phase
    run: mvn --batch-mode --update-snapshots verify
  - name: Compile code
    run: mvn test-compile -pl flink-libraries/flink-cep -am
  - name: running regular test
    run:  mvn -pl flink-libraries/flink-cep test -Dtest=org.apache.flink.cep.operator.CEPOperatorTest#testCEPOperatorComparatorEventTime
  - name: Running test using NonDex Tool
    run: mvn -pl flink-libraries/flink-cep edu.illinois:nondex-maven-plugin:1.1.2:nondex -Dtest=org.apache.flink.cep.operator.CEPOperatorTest#testCEPOperatorComparatorEventTime
